language: groovy
jdk:
  - oraclejdk8
env:
  - "LIB_GRADLE_VERSION=3.0"
  - "LIB_GRADLE_VERSION=3.3"
  - "LIB_GRADLE_VERSION=3.4.1"
  - "LIB_GRADLE_VERSION=3.5.1"
  - "LIB_GRADLE_VERSION=4.0.1"
  - "LIB_GRADLE_VERSION=4.1"
  - "LIB_GRADLE_VERSION=4.2.1"
install:
  - gradle wrapper
  - ./gradlew uploadArchives
